### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by abalakersky** [drelyn86/atom-terminus#3]
[Enter steps to reproduce below:]
1. open command pallete and find terminal "open project root"
2. ...

**Atom Version**: 1.5.3
**System**: Linux Mint
**Thrown From**: [atom-terminus](https://github.com/drelyn86/atom-terminus) package, v1.0.1
### Stack Trace

Uncaught TypeError: Cannot read property 'replace' of undefined

```
At /home/abalakersky/.atom/packages/atom-terminus/lib/atom-terminus.coffee:27

TypeError: Cannot read property 'replace' of undefined
    at open_terminal (/home/abalakersky/.atom/packages/atom-terminus/lib/atom-terminus.coffee:27:36)
    at Object.module.exports.openroot (/home/abalakersky/.atom/packages/atom-terminus/lib/atom-terminus.coffee:91:7)
    at atom-workspace.<anonymous> (/home/abalakersky/.atom/packages/atom-terminus/lib/atom-terminus.coffee:66:99)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:260:29)
    at /opt/atom/resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/opt/atom/resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/opt/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/opt/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:260:29)
    at /opt/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:544:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:363:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/opt/atom/resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/opt/atom/resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -0:46.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:46.6.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:46.6.0 w (atom-text-editor.editor.vim-mode-plus.normal-mode)
     -0:23.1.0 command-palette:toggle (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:22.8.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:20.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:20.9.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:20.9.0 atom-terminus:open (atom-text-editor.editor.vim-mode-plus.normal-mode)
  2x -0:20.7.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:07.0 command-palette:toggle (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:06.8.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
  2x -0:04.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:01.3.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:00.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.7.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:00.7.0 atom-terminus:open-project-root (atom-text-editor.editor.vim-mode-plus.normal-mode)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "language-gfm"
    ],
    "projectHome": "/home/abalakersky/Development"
  },
  "atom-terminus": {
    "app": "/usr/bin/terminator"
  }
}
```
### Installed Packages

``` coffee
# User
atom-json-editor, v0.4.1
atom-terminus, v1.0.1
atom-vim-colon-command-on-command-pallete, v0.2.0
atom-yamljson, v0.2.3
autocomplete-python, v1.6.1
autocomplete-ruby, v0.1.0
clipboard-plus, v0.5.1
colorful-json, v1.0.0
git-plus, v5.13.0
git-status, v0.3.4
go-plus, v3.5.3
language-markdown, v0.11.0
linter, v1.11.3
linter-ruby, v1.2.1
markdown-themeable-pdf, v0.10.2
pretty-json, v0.4.1
python-tools, v0.6.7
ruby-block, v0.3.5
ruby-block-converter, v3.5.0
ruby-define-method, v0.2.2
vim-mode-clipboard-plus, v0.2.0
vim-mode-plus, v0.20.0

# Dev
No dev packages
```

**Comment by duhdugg** [comment]
@abalakersky Thanks for bringing this to my attention. This is fixed now in version 1.1.0.
